"""Default filesystem locations shared by every script.

Centralized so scripts can live in nested folders without each one
re-deriving the repo root from its own `__file__`, and so the
results/ layout is defined in exactly one place.
"""

from pathlib import Path

# segmentation/paths.py -> segmentation/ -> repo root
REPO_ROOT = Path(__file__).resolve().parent.parent

# Dataset: frames + per-class masks (training/) and the official
# pre-merged test masks (test/).
DATASET_ROOT = REPO_ROOT / "dataset" / "training"
TEST_ROOT = REPO_ROOT / "dataset" / "test"

CHECKPOINT_DIR = REPO_ROOT / "checkpoints"
DEFAULT_CHECKPOINT = CHECKPOINT_DIR / "unet_resnet34.pt"

# Reference numbers transcribed from published papers.
REFERENCE_DIR = REPO_ROOT / "reference"
CHALLENGE_RESULTS = REFERENCE_DIR / "endovis2017_binary_results.json"

# Everything generated by the scripts lands under results/.
RESULTS_DIR = REPO_ROOT / "results"
METRICS_DIR = RESULTS_DIR / "metrics"  # per-method evaluation JSON
LOGS_DIR = RESULTS_DIR / "logs"  # training logs
OVERLAYS_DIR = RESULTS_DIR / "overlays"  # qualitative prediction images
FIGURES_DIR = RESULTS_DIR / "figures"  # plots (PNG)
TABLES_DIR = RESULTS_DIR / "tables"  # comparison tables (Markdown/CSV)

BASELINE_METRICS = METRICS_DIR / "baseline_threshold.json"
MODEL_METRICS = METRICS_DIR / "model_eval.json"
TRAIN_LOG = LOGS_DIR / "train_log.csv"
